num1 = int(input("Enter a num1 "))
print("num1 = ", num1)
num2 = int(input("Enter a num2 "))
print("num2 = ", num1)
print("performing some basic arithmetic operations")
div = (num1/num2)
print('Division of ',num1 ,'and' ,num2 ,'is :',div)
add = (num1+num2)
print('Addition of ',num1 ,'and' ,num2 ,'is :',add)
mul = (num1*num2)
print('Multiplication of ',num1 ,'and' ,num2 ,'is :',mul)
sub= (num1-num2)
print('Difference of ',num1 ,'and' ,num2 ,'is :',sub)
power = (num1 ** num2)
print('Power of ',num1 ,'and' ,num2 ,'is :',power)